/** Shared Phosphor icon registry. SSR imports also render safely in client components.
 * Use regular line icons throughout the product UI.
 */
import { forwardRef } from "react";
import type { Icon as AppIcon, IconProps as AppIconProps } from "@phosphor-icons/react";
import { ArrowCounterClockwiseIcon } from "@phosphor-icons/react/dist/ssr/ArrowCounterClockwise";
import { ArrowDownIcon } from "@phosphor-icons/react/dist/ssr/ArrowDown";
import { ArrowDownLeftIcon } from "@phosphor-icons/react/dist/ssr/ArrowDownLeft";
import { ArrowDownRightIcon } from "@phosphor-icons/react/dist/ssr/ArrowDownRight";
import { ArrowLeftIcon } from "@phosphor-icons/react/dist/ssr/ArrowLeft";
import { ArrowRightIcon } from "@phosphor-icons/react/dist/ssr/ArrowRight";
import { ArrowSquareOutIcon } from "@phosphor-icons/react/dist/ssr/ArrowSquareOut";
import { ArrowUpIcon } from "@phosphor-icons/react/dist/ssr/ArrowUp";
import { ArrowUpRightIcon } from "@phosphor-icons/react/dist/ssr/ArrowUpRight";
import { ArrowsClockwiseIcon } from "@phosphor-icons/react/dist/ssr/ArrowsClockwise";
import { ArrowsCounterClockwiseIcon } from "@phosphor-icons/react/dist/ssr/ArrowsCounterClockwise";
import { ArrowsDownUpIcon } from "@phosphor-icons/react/dist/ssr/ArrowsDownUp";
import { ArrowsLeftRightIcon } from "@phosphor-icons/react/dist/ssr/ArrowsLeftRight";
import { BankIcon } from "@phosphor-icons/react/dist/ssr/Bank";
import { BellIcon } from "@phosphor-icons/react/dist/ssr/Bell";
import { BellRingingIcon } from "@phosphor-icons/react/dist/ssr/BellRinging";
import { BookOpenIcon } from "@phosphor-icons/react/dist/ssr/BookOpen";
import { BookmarkSimpleIcon } from "@phosphor-icons/react/dist/ssr/BookmarkSimple";
import { BroadcastIcon } from "@phosphor-icons/react/dist/ssr/Broadcast";
import { BuildingsIcon } from "@phosphor-icons/react/dist/ssr/Buildings";
import { CalculatorIcon } from "@phosphor-icons/react/dist/ssr/Calculator";
import { CalendarBlankIcon } from "@phosphor-icons/react/dist/ssr/CalendarBlank";
import { CaretDoubleLeftIcon } from "@phosphor-icons/react/dist/ssr/CaretDoubleLeft";
import { CaretDoubleRightIcon } from "@phosphor-icons/react/dist/ssr/CaretDoubleRight";
import { CaretDownIcon } from "@phosphor-icons/react/dist/ssr/CaretDown";
import { CaretLeftIcon } from "@phosphor-icons/react/dist/ssr/CaretLeft";
import { CaretRightIcon } from "@phosphor-icons/react/dist/ssr/CaretRight";
import { CaretUpIcon } from "@phosphor-icons/react/dist/ssr/CaretUp";
import { CaretUpDownIcon } from "@phosphor-icons/react/dist/ssr/CaretUpDown";
import { ChartBarIcon } from "@phosphor-icons/react/dist/ssr/ChartBar";
import { ChartLineIcon } from "@phosphor-icons/react/dist/ssr/ChartLine";
import { ChartPieSliceIcon } from "@phosphor-icons/react/dist/ssr/ChartPieSlice";
import { ChatCircleDotsIcon } from "@phosphor-icons/react/dist/ssr/ChatCircleDots";
import { CheckIcon } from "@phosphor-icons/react/dist/ssr/Check";
import { CheckCircleIcon } from "@phosphor-icons/react/dist/ssr/CheckCircle";
import { CheckSquareIcon } from "@phosphor-icons/react/dist/ssr/CheckSquare";
import { ChecksIcon } from "@phosphor-icons/react/dist/ssr/Checks";
import { CircleIcon } from "@phosphor-icons/react/dist/ssr/Circle";
import { CircleNotchIcon } from "@phosphor-icons/react/dist/ssr/CircleNotch";
import { ClipboardTextIcon } from "@phosphor-icons/react/dist/ssr/ClipboardText";
import { ClockIcon } from "@phosphor-icons/react/dist/ssr/Clock";
import { ClockCounterClockwiseIcon } from "@phosphor-icons/react/dist/ssr/ClockCounterClockwise";
import { CloudArrowUpIcon } from "@phosphor-icons/react/dist/ssr/CloudArrowUp";
import { CodeIcon } from "@phosphor-icons/react/dist/ssr/Code";
import { CoinsIcon } from "@phosphor-icons/react/dist/ssr/Coins";
import { ColumnsIcon } from "@phosphor-icons/react/dist/ssr/Columns";
import { CompassIcon } from "@phosphor-icons/react/dist/ssr/Compass";
import { CopySimpleIcon } from "@phosphor-icons/react/dist/ssr/CopySimple";
import { CpuIcon } from "@phosphor-icons/react/dist/ssr/Cpu";
import { CurrencyDollarIcon } from "@phosphor-icons/react/dist/ssr/CurrencyDollar";
import { DatabaseIcon } from "@phosphor-icons/react/dist/ssr/Database";
import { DotsSixVerticalIcon } from "@phosphor-icons/react/dist/ssr/DotsSixVertical";
import { DotsThreeIcon } from "@phosphor-icons/react/dist/ssr/DotsThree";
import { DownloadSimpleIcon } from "@phosphor-icons/react/dist/ssr/DownloadSimple";
import { EnvelopeSimpleIcon } from "@phosphor-icons/react/dist/ssr/EnvelopeSimple";
import { EyeIcon } from "@phosphor-icons/react/dist/ssr/Eye";
import { EyeSlashIcon } from "@phosphor-icons/react/dist/ssr/EyeSlash";
import { FileArrowDownIcon } from "@phosphor-icons/react/dist/ssr/FileArrowDown";
import { FileArrowUpIcon } from "@phosphor-icons/react/dist/ssr/FileArrowUp";
import { FileCodeIcon } from "@phosphor-icons/react/dist/ssr/FileCode";
import { FileMagnifyingGlassIcon } from "@phosphor-icons/react/dist/ssr/FileMagnifyingGlass";
import { FileTextIcon } from "@phosphor-icons/react/dist/ssr/FileText";
import { FileXIcon } from "@phosphor-icons/react/dist/ssr/FileX";
import { FileXlsIcon } from "@phosphor-icons/react/dist/ssr/FileXls";
import { FingerprintIcon } from "@phosphor-icons/react/dist/ssr/Fingerprint";
import { FireIcon } from "@phosphor-icons/react/dist/ssr/Fire";
import { FloppyDiskIcon } from "@phosphor-icons/react/dist/ssr/FloppyDisk";
import { FlowArrowIcon } from "@phosphor-icons/react/dist/ssr/FlowArrow";
import { FolderOpenIcon } from "@phosphor-icons/react/dist/ssr/FolderOpen";
import { FunnelSimpleIcon } from "@phosphor-icons/react/dist/ssr/FunnelSimple";
import { GaugeIcon } from "@phosphor-icons/react/dist/ssr/Gauge";
import { GearSixIcon } from "@phosphor-icons/react/dist/ssr/GearSix";
import { GitBranchIcon } from "@phosphor-icons/react/dist/ssr/GitBranch";
import { GraphIcon } from "@phosphor-icons/react/dist/ssr/Graph";
import { HardDrivesIcon } from "@phosphor-icons/react/dist/ssr/HardDrives";
import { HashIcon } from "@phosphor-icons/react/dist/ssr/Hash";
import { HouseSimpleIcon } from "@phosphor-icons/react/dist/ssr/HouseSimple";
import { InfoIcon } from "@phosphor-icons/react/dist/ssr/Info";
import { KeyIcon } from "@phosphor-icons/react/dist/ssr/Key";
import { LifebuoyIcon } from "@phosphor-icons/react/dist/ssr/Lifebuoy";
import { LightningIcon } from "@phosphor-icons/react/dist/ssr/Lightning";
import { ListIcon } from "@phosphor-icons/react/dist/ssr/List";
import { LockSimpleIcon } from "@phosphor-icons/react/dist/ssr/LockSimple";
import { MagnifyingGlassIcon } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { MagnifyingGlassPlusIcon } from "@phosphor-icons/react/dist/ssr/MagnifyingGlassPlus";
import { MinusIcon } from "@phosphor-icons/react/dist/ssr/Minus";
import { MoneyIcon } from "@phosphor-icons/react/dist/ssr/Money";
import { MoonStarsIcon } from "@phosphor-icons/react/dist/ssr/MoonStars";
import { PaperPlaneTiltIcon } from "@phosphor-icons/react/dist/ssr/PaperPlaneTilt";
import { PlayIcon } from "@phosphor-icons/react/dist/ssr/Play";
import { PlayCircleIcon } from "@phosphor-icons/react/dist/ssr/PlayCircle";
import { PlusIcon } from "@phosphor-icons/react/dist/ssr/Plus";
import { PrinterIcon } from "@phosphor-icons/react/dist/ssr/Printer";
import { ProhibitIcon } from "@phosphor-icons/react/dist/ssr/Prohibit";
import { PulseIcon } from "@phosphor-icons/react/dist/ssr/Pulse";
import { QuestionIcon } from "@phosphor-icons/react/dist/ssr/Question";
import { ReceiptIcon } from "@phosphor-icons/react/dist/ssr/Receipt";
import { RobotIcon } from "@phosphor-icons/react/dist/ssr/Robot";
import { RocketLaunchIcon } from "@phosphor-icons/react/dist/ssr/RocketLaunch";
import { ScalesIcon } from "@phosphor-icons/react/dist/ssr/Scales";
import { ShieldIcon } from "@phosphor-icons/react/dist/ssr/Shield";
import { ShieldCheckIcon } from "@phosphor-icons/react/dist/ssr/ShieldCheck";
import { ShieldWarningIcon } from "@phosphor-icons/react/dist/ssr/ShieldWarning";
import { SidebarSimpleIcon } from "@phosphor-icons/react/dist/ssr/SidebarSimple";
import { SignOutIcon } from "@phosphor-icons/react/dist/ssr/SignOut";
import { SlidersHorizontalIcon } from "@phosphor-icons/react/dist/ssr/SlidersHorizontal";
import { SparkleIcon } from "@phosphor-icons/react/dist/ssr/Sparkle";
import { SquaresFourIcon } from "@phosphor-icons/react/dist/ssr/SquaresFour";
import { StackIcon } from "@phosphor-icons/react/dist/ssr/Stack";
import { StarIcon } from "@phosphor-icons/react/dist/ssr/Star";
import { SunIcon } from "@phosphor-icons/react/dist/ssr/Sun";
import { TableIcon } from "@phosphor-icons/react/dist/ssr/Table";
import { TargetIcon } from "@phosphor-icons/react/dist/ssr/Target";
import { TerminalWindowIcon } from "@phosphor-icons/react/dist/ssr/TerminalWindow";
import { TrashIcon } from "@phosphor-icons/react/dist/ssr/Trash";
import { TrayIcon } from "@phosphor-icons/react/dist/ssr/Tray";
import { TrendDownIcon } from "@phosphor-icons/react/dist/ssr/TrendDown";
import { TrendUpIcon } from "@phosphor-icons/react/dist/ssr/TrendUp";
import { TruckIcon } from "@phosphor-icons/react/dist/ssr/Truck";
import { UserIcon } from "@phosphor-icons/react/dist/ssr/User";
import { UserCheckIcon } from "@phosphor-icons/react/dist/ssr/UserCheck";
import { UserPlusIcon } from "@phosphor-icons/react/dist/ssr/UserPlus";
import { UsersIcon } from "@phosphor-icons/react/dist/ssr/Users";
import { UsersThreeIcon } from "@phosphor-icons/react/dist/ssr/UsersThree";
import { WalletIcon } from "@phosphor-icons/react/dist/ssr/Wallet";
import { WarningIcon } from "@phosphor-icons/react/dist/ssr/Warning";
import { WarningCircleIcon } from "@phosphor-icons/react/dist/ssr/WarningCircle";
import { WarningOctagonIcon } from "@phosphor-icons/react/dist/ssr/WarningOctagon";
import { WifiHighIcon } from "@phosphor-icons/react/dist/ssr/WifiHigh";
import { WifiSlashIcon } from "@phosphor-icons/react/dist/ssr/WifiSlash";
import { XIcon } from "@phosphor-icons/react/dist/ssr/X";
import { XCircleIcon } from "@phosphor-icons/react/dist/ssr/XCircle";

export type { AppIcon, AppIconProps };

function productIcon(Icon: AppIcon, name: string): AppIcon {
  const Component = forwardRef<SVGSVGElement, AppIconProps>(({ weight = "regular", size = 24, ...props }, ref) => (
    <Icon ref={ref} weight={weight} size={size} aria-hidden={props["aria-label"] || props.alt ? undefined : true} data-icon={name} {...props} />
  ));
  Component.displayName = name;
  return Component;
}

export const Activity = /* @__PURE__ */ productIcon(PulseIcon, "Activity");
export const AlertCircle = /* @__PURE__ */ productIcon(WarningCircleIcon, "AlertCircle");
export const AlertOctagon = /* @__PURE__ */ productIcon(WarningOctagonIcon, "AlertOctagon");
export const AlertTriangle = /* @__PURE__ */ productIcon(WarningIcon, "AlertTriangle");
export const ArrowDown = /* @__PURE__ */ productIcon(ArrowDownIcon, "ArrowDown");
export const ArrowDownLeft = /* @__PURE__ */ productIcon(ArrowDownLeftIcon, "ArrowDownLeft");
export const ArrowDownRight = /* @__PURE__ */ productIcon(ArrowDownRightIcon, "ArrowDownRight");
export const ArrowLeft = /* @__PURE__ */ productIcon(ArrowLeftIcon, "ArrowLeft");
export const ArrowLeftRight = /* @__PURE__ */ productIcon(ArrowsLeftRightIcon, "ArrowLeftRight");
export const ArrowRight = /* @__PURE__ */ productIcon(ArrowRightIcon, "ArrowRight");
export const ArrowRightLeft = /* @__PURE__ */ productIcon(ArrowsLeftRightIcon, "ArrowRightLeft");
export const ArrowUp = /* @__PURE__ */ productIcon(ArrowUpIcon, "ArrowUp");
export const ArrowUpDown = /* @__PURE__ */ productIcon(ArrowsDownUpIcon, "ArrowUpDown");
export const ArrowUpRight = /* @__PURE__ */ productIcon(ArrowUpRightIcon, "ArrowUpRight");
export const Ban = /* @__PURE__ */ productIcon(ProhibitIcon, "Ban");
export const Banknote = /* @__PURE__ */ productIcon(MoneyIcon, "Banknote");
export const BarChart3 = /* @__PURE__ */ productIcon(ChartBarIcon, "BarChart3");
export const Bell = /* @__PURE__ */ productIcon(BellIcon, "Bell");
export const BellRing = /* @__PURE__ */ productIcon(BellRingingIcon, "BellRing");
export const BookOpen = /* @__PURE__ */ productIcon(BookOpenIcon, "BookOpen");
export const Bookmark = /* @__PURE__ */ productIcon(BookmarkSimpleIcon, "Bookmark");
export const BookmarkPlus = /* @__PURE__ */ productIcon(BookmarkSimpleIcon, "BookmarkPlus");
export const Bot = /* @__PURE__ */ productIcon(RobotIcon, "Bot");
export const Building2 = /* @__PURE__ */ productIcon(BuildingsIcon, "Building2");
export const Calculator = /* @__PURE__ */ productIcon(CalculatorIcon, "Calculator");
export const Calendar = /* @__PURE__ */ productIcon(CalendarBlankIcon, "Calendar");
export const Check = /* @__PURE__ */ productIcon(CheckIcon, "Check");
export const CheckCheck = /* @__PURE__ */ productIcon(ChecksIcon, "CheckCheck");
export const CheckCircle = /* @__PURE__ */ productIcon(CheckCircleIcon, "CheckCircle");
export const CheckCircle2 = /* @__PURE__ */ productIcon(CheckCircleIcon, "CheckCircle2");
export const CheckSquare = /* @__PURE__ */ productIcon(CheckSquareIcon, "CheckSquare");
export const ChevronDown = /* @__PURE__ */ productIcon(CaretDownIcon, "ChevronDown");
export const ChevronDownIcon = /* @__PURE__ */ productIcon(CaretDownIcon, "ChevronDownIcon");
export const ChevronLeft = /* @__PURE__ */ productIcon(CaretLeftIcon, "ChevronLeft");
export const ChevronLeftIcon = /* @__PURE__ */ productIcon(CaretLeftIcon, "ChevronLeftIcon");
export const ChevronRight = /* @__PURE__ */ productIcon(CaretRightIcon, "ChevronRight");
export const ChevronRightIcon = /* @__PURE__ */ productIcon(CaretRightIcon, "ChevronRightIcon");
export const ChevronUp = /* @__PURE__ */ productIcon(CaretUpIcon, "ChevronUp");
export const ChevronsLeft = /* @__PURE__ */ productIcon(CaretDoubleLeftIcon, "ChevronsLeft");
export const ChevronsRight = /* @__PURE__ */ productIcon(CaretDoubleRightIcon, "ChevronsRight");
export const ChevronsUpDown = /* @__PURE__ */ productIcon(CaretUpDownIcon, "ChevronsUpDown");
export const Circle = /* @__PURE__ */ productIcon(CircleIcon, "Circle");
export const ClipboardCheck = /* @__PURE__ */ productIcon(ClipboardTextIcon, "ClipboardCheck");
export const Clock = /* @__PURE__ */ productIcon(ClockIcon, "Clock");
export const Code = /* @__PURE__ */ productIcon(CodeIcon, "Code");
export const Coins = /* @__PURE__ */ productIcon(CoinsIcon, "Coins");
export const Columns = /* @__PURE__ */ productIcon(ColumnsIcon, "Columns");
export const Compass = /* @__PURE__ */ productIcon(CompassIcon, "Compass");
export const Copy = /* @__PURE__ */ productIcon(CopySimpleIcon, "Copy");
export const Cpu = /* @__PURE__ */ productIcon(CpuIcon, "Cpu");
export const Database = /* @__PURE__ */ productIcon(DatabaseIcon, "Database");
export const DollarSign = /* @__PURE__ */ productIcon(CurrencyDollarIcon, "DollarSign");
export const Download = /* @__PURE__ */ productIcon(DownloadSimpleIcon, "Download");
export const ExternalLink = /* @__PURE__ */ productIcon(ArrowSquareOutIcon, "ExternalLink");
export const Eye = /* @__PURE__ */ productIcon(EyeIcon, "Eye");
export const EyeOff = /* @__PURE__ */ productIcon(EyeSlashIcon, "EyeOff");
export const FileCheck = /* @__PURE__ */ productIcon(FileTextIcon, "FileCheck");
export const FileCheck2 = /* @__PURE__ */ productIcon(FileTextIcon, "FileCheck2");
export const FileCode2 = /* @__PURE__ */ productIcon(FileCodeIcon, "FileCode2");
export const FileDown = /* @__PURE__ */ productIcon(FileArrowDownIcon, "FileDown");
export const FileQuestion = /* @__PURE__ */ productIcon(FileMagnifyingGlassIcon, "FileQuestion");
export const FileSpreadsheet = /* @__PURE__ */ productIcon(FileXlsIcon, "FileSpreadsheet");
export const FileText = /* @__PURE__ */ productIcon(FileTextIcon, "FileText");
export const FileUp = /* @__PURE__ */ productIcon(FileArrowUpIcon, "FileUp");
export const FileX2 = /* @__PURE__ */ productIcon(FileXIcon, "FileX2");
export const Filter = /* @__PURE__ */ productIcon(FunnelSimpleIcon, "Filter");
export const Fingerprint = /* @__PURE__ */ productIcon(FingerprintIcon, "Fingerprint");
export const Flame = /* @__PURE__ */ productIcon(FireIcon, "Flame");
export const FolderSearch = /* @__PURE__ */ productIcon(FolderOpenIcon, "FolderSearch");
export const Gauge = /* @__PURE__ */ productIcon(GaugeIcon, "Gauge");
export const GitBranch = /* @__PURE__ */ productIcon(GitBranchIcon, "GitBranch");
export const GripVerticalIcon = /* @__PURE__ */ productIcon(DotsSixVerticalIcon, "GripVerticalIcon");
export const HardDrive = /* @__PURE__ */ productIcon(HardDrivesIcon, "HardDrive");
export const Hash = /* @__PURE__ */ productIcon(HashIcon, "Hash");
export const HelpCircle = /* @__PURE__ */ productIcon(QuestionIcon, "HelpCircle");
export const History = /* @__PURE__ */ productIcon(ClockCounterClockwiseIcon, "History");
export const Home = /* @__PURE__ */ productIcon(HouseSimpleIcon, "Home");
export const Inbox = /* @__PURE__ */ productIcon(TrayIcon, "Inbox");
export const Info = /* @__PURE__ */ productIcon(InfoIcon, "Info");
export const Key = /* @__PURE__ */ productIcon(KeyIcon, "Key");
export const Landmark = /* @__PURE__ */ productIcon(BankIcon, "Landmark");
export const Layers = /* @__PURE__ */ productIcon(StackIcon, "Layers");
export const LayoutDashboard = /* @__PURE__ */ productIcon(SquaresFourIcon, "LayoutDashboard");
export const LifeBuoy = /* @__PURE__ */ productIcon(LifebuoyIcon, "LifeBuoy");
export const LineChart = /* @__PURE__ */ productIcon(ChartLineIcon, "LineChart");
export const ListFilter = /* @__PURE__ */ productIcon(FunnelSimpleIcon, "ListFilter");
export const Loader2 = /* @__PURE__ */ productIcon(CircleNotchIcon, "Loader2");
export const Loader2Icon = /* @__PURE__ */ productIcon(CircleNotchIcon, "Loader2Icon");
export const Lock = /* @__PURE__ */ productIcon(LockSimpleIcon, "Lock");
export const LogOut = /* @__PURE__ */ productIcon(SignOutIcon, "LogOut");
export const Mail = /* @__PURE__ */ productIcon(EnvelopeSimpleIcon, "Mail");
export const Menu = /* @__PURE__ */ productIcon(ListIcon, "Menu");
export const MessageSquarePlus = /* @__PURE__ */ productIcon(ChatCircleDotsIcon, "MessageSquarePlus");
export const Minus = /* @__PURE__ */ productIcon(MinusIcon, "Minus");
export const Moon = /* @__PURE__ */ productIcon(MoonStarsIcon, "Moon");
export const MoreHorizontal = /* @__PURE__ */ productIcon(DotsThreeIcon, "MoreHorizontal");
export const Network = /* @__PURE__ */ productIcon(GraphIcon, "Network");
export const PanelLeft = /* @__PURE__ */ productIcon(SidebarSimpleIcon, "PanelLeft");
export const PieChart = /* @__PURE__ */ productIcon(ChartPieSliceIcon, "PieChart");
export const Play = /* @__PURE__ */ productIcon(PlayIcon, "Play");
export const PlayCircle = /* @__PURE__ */ productIcon(PlayCircleIcon, "PlayCircle");
export const Plus = /* @__PURE__ */ productIcon(PlusIcon, "Plus");
export const Printer = /* @__PURE__ */ productIcon(PrinterIcon, "Printer");
export const Radio = /* @__PURE__ */ productIcon(BroadcastIcon, "Radio");
export const Receipt = /* @__PURE__ */ productIcon(ReceiptIcon, "Receipt");
export const RefreshCcw = /* @__PURE__ */ productIcon(ArrowsCounterClockwiseIcon, "RefreshCcw");
export const RefreshCw = /* @__PURE__ */ productIcon(ArrowsClockwiseIcon, "RefreshCw");
export const Rocket = /* @__PURE__ */ productIcon(RocketLaunchIcon, "Rocket");
export const RotateCcw = /* @__PURE__ */ productIcon(ArrowCounterClockwiseIcon, "RotateCcw");
export const Save = /* @__PURE__ */ productIcon(FloppyDiskIcon, "Save");
export const Scale = /* @__PURE__ */ productIcon(ScalesIcon, "Scale");
export const ScanSearch = /* @__PURE__ */ productIcon(MagnifyingGlassPlusIcon, "ScanSearch");
export const Search = /* @__PURE__ */ productIcon(MagnifyingGlassIcon, "Search");
export const Send = /* @__PURE__ */ productIcon(PaperPlaneTiltIcon, "Send");
export const Server = /* @__PURE__ */ productIcon(HardDrivesIcon, "Server");
export const Settings = /* @__PURE__ */ productIcon(GearSixIcon, "Settings");
export const Shield = /* @__PURE__ */ productIcon(ShieldIcon, "Shield");
export const ShieldAlert = /* @__PURE__ */ productIcon(ShieldWarningIcon, "ShieldAlert");
export const ShieldCheck = /* @__PURE__ */ productIcon(ShieldCheckIcon, "ShieldCheck");
export const SlidersHorizontal = /* @__PURE__ */ productIcon(SlidersHorizontalIcon, "SlidersHorizontal");
export const Sparkles = /* @__PURE__ */ productIcon(SparkleIcon, "Sparkles");
export const Star = /* @__PURE__ */ productIcon(StarIcon, "Star");
export const Sun = /* @__PURE__ */ productIcon(SunIcon, "Sun");
export const Table = /* @__PURE__ */ productIcon(TableIcon, "Table");
export const Target = /* @__PURE__ */ productIcon(TargetIcon, "Target");
export const Terminal = /* @__PURE__ */ productIcon(TerminalWindowIcon, "Terminal");
export const Trash2 = /* @__PURE__ */ productIcon(TrashIcon, "Trash2");
export const TrendingDown = /* @__PURE__ */ productIcon(TrendDownIcon, "TrendingDown");
export const TrendingUp = /* @__PURE__ */ productIcon(TrendUpIcon, "TrendingUp");
export const TriangleAlert = /* @__PURE__ */ productIcon(WarningIcon, "TriangleAlert");
export const Truck = /* @__PURE__ */ productIcon(TruckIcon, "Truck");
export const UploadCloud = /* @__PURE__ */ productIcon(CloudArrowUpIcon, "UploadCloud");
export const User = /* @__PURE__ */ productIcon(UserIcon, "User");
export const UserCheck = /* @__PURE__ */ productIcon(UserCheckIcon, "UserCheck");
export const UserPlus = /* @__PURE__ */ productIcon(UserPlusIcon, "UserPlus");
export const Users = /* @__PURE__ */ productIcon(UsersIcon, "Users");
export const Users2 = /* @__PURE__ */ productIcon(UsersThreeIcon, "Users2");
export const Wallet = /* @__PURE__ */ productIcon(WalletIcon, "Wallet");
export const WalletCards = /* @__PURE__ */ productIcon(WalletIcon, "WalletCards");
export const Wifi = /* @__PURE__ */ productIcon(WifiHighIcon, "Wifi");
export const WifiOff = /* @__PURE__ */ productIcon(WifiSlashIcon, "WifiOff");
export const Workflow = /* @__PURE__ */ productIcon(FlowArrowIcon, "Workflow");
export const X = /* @__PURE__ */ productIcon(XIcon, "X");
export const XCircle = /* @__PURE__ */ productIcon(XCircleIcon, "XCircle");
export const Zap = /* @__PURE__ */ productIcon(LightningIcon, "Zap");
