"""phase 5 canonical financial model

Revision ID: 57635d980143
Revises: 20260913_0004
Create Date: 2026-09-13 05:22:45.382517
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "57635d980143"
down_revision: str | None = "20260913_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CANONICAL_TABLES = (
    "accounts",
    "counterparties",
    "bank_accounts",
    "bank_transactions",
    "journal_entries",
    "journal_lines",
    "sales_invoices",
)


def enable_rls(table: str) -> None:
    op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE public.{table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY {table}_select ON public.{table} FOR SELECT "
        "USING (private.has_company_role(company_id, "
        "ARRAY['OWNER','FINANCE_MANAGER','ADVISOR','VIEWER']))"
    )
    op.execute(
        f"CREATE POLICY {table}_insert ON public.{table} FOR INSERT "
        "WITH CHECK (private.has_company_role(company_id, "
        "ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']))"
    )
    op.execute(f"GRANT SELECT, INSERT ON public.{table} TO didban_app")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_data_source_company", "data_sources", ["id", "company_id"])
    op.create_table(
        "accounts",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_code", sa.String(length=160), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "source_code", name="uq_account_company_code"),
        sa.UniqueConstraint("id", "company_id", name="uq_account_company"),
    )
    op.create_index(
        "ix_accounts_company_normalized_name",
        "accounts",
        ["company_id", "normalized_name"],
        unique=False,
    )
    op.create_table(
        "counterparties",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("national_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "normalized_name", name="uq_counterparty_company_name"),
        sa.UniqueConstraint("id", "company_id", name="uq_counterparty_company"),
    )
    op.create_index(
        "ix_counterparties_company_national_id",
        "counterparties",
        ["company_id", "national_id"],
        unique=False,
    )
    op.create_table(
        "account_classifications",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "account_class",
            sa.Enum(
                "ASSET",
                "LIABILITY",
                "EQUITY",
                "REVENUE",
                "EXPENSE",
                "OTHER",
                name="account_class",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("confirmed_by", sa.UUID(), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id", "company_id"], ["accounts.id", "accounts.company_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["confirmed_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "effective_from", name="uq_account_classification_effective"
        ),
    )
    op.create_index(
        "ix_account_classifications_company_account",
        "account_classifications",
        ["company_id", "account_id"],
        unique=False,
    )
    op.create_index(
        "ix_account_classifications_confirmed_by",
        "account_classifications",
        ["confirmed_by"],
        unique=False,
    )
    op.create_table(
        "bank_accounts",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("data_source_id", sa.UUID(), nullable=False),
        sa.Column("bank_name", sa.String(length=160), nullable=False),
        sa.Column("iban_masked", sa.String(length=34), nullable=True),
        sa.Column("account_last4", sa.String(length=4), nullable=True),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["data_source_id", "company_id"],
            ["data_sources.id", "data_sources.company_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", name="uq_bank_account_data_source"),
        sa.UniqueConstraint("id", "company_id", name="uq_bank_account_company"),
    )
    op.create_index(
        "ix_bank_accounts_company_label", "bank_accounts", ["company_id", "label"], unique=False
    )
    op.create_table(
        "bank_transactions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("bank_account_id", sa.UUID(), nullable=False),
        sa.Column("source_row_id", sa.UUID(), nullable=False),
        sa.Column("source_transaction_id", sa.String(length=300), nullable=True),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount_irr", sa.Numeric(precision=20, scale=0), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("description_normalized", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=300), nullable=True),
        sa.Column("running_balance_irr", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_account_id", "company_id"],
            ["bank_accounts.id", "bank_accounts.company_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_row_id", "company_id"],
            ["source_rows.id", "source_rows.company_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_row_id", name="uq_bank_transaction_source_row"),
    )
    op.create_index(
        "ix_bank_transactions_bank_account", "bank_transactions", ["bank_account_id"], unique=False
    )
    op.create_index(
        "ix_bank_transactions_company_date",
        "bank_transactions",
        ["company_id", "booking_date"],
        unique=False,
    )
    op.create_table(
        "journal_entries",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("import_batch_id", sa.UUID(), nullable=False),
        sa.Column("source_row_id", sa.UUID(), nullable=False),
        sa.Column("source_entry_key", sa.String(length=200), nullable=False),
        sa.Column("source_entry_id", sa.String(length=200), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("reference", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("description_normalized", sa.Text(), nullable=False),
        sa.Column("fiscal_period", sa.String(length=7), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["import_batch_id", "company_id"],
            ["import_batches.id", "import_batches.company_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id", "company_id"],
            ["source_rows.id", "source_rows.company_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "company_id", name="uq_journal_entry_company"),
        sa.UniqueConstraint(
            "import_batch_id", "source_entry_key", name="uq_journal_entry_batch_key"
        ),
    )
    op.create_index(
        "ix_journal_entries_company_date",
        "journal_entries",
        ["company_id", "entry_date"],
        unique=False,
    )
    op.create_index(
        "ix_journal_entries_source_row", "journal_entries", ["source_row_id"], unique=False
    )
    op.create_table(
        "sales_invoices",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_row_id", sa.UUID(), nullable=False),
        sa.Column("invoice_no", sa.String(length=300), nullable=False),
        sa.Column("counterparty_id", sa.UUID(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("gross_amount_irr", sa.Numeric(precision=20, scale=0), nullable=False),
        sa.Column("tax_amount_irr", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("paid_amount_irr", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("gross_amount_irr >= 0", name="ck_sales_invoice_gross_nonnegative"),
        sa.CheckConstraint(
            "paid_amount_irr IS NULL OR paid_amount_irr >= 0",
            name="ck_sales_invoice_paid_nonnegative",
        ),
        sa.CheckConstraint(
            "tax_amount_irr IS NULL OR tax_amount_irr >= 0", name="ck_sales_invoice_tax_nonnegative"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["counterparty_id", "company_id"],
            ["counterparties.id", "counterparties.company_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id", "company_id"],
            ["source_rows.id", "source_rows.company_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "invoice_no", "issue_date", name="uq_sales_invoice_logical"
        ),
        sa.UniqueConstraint("source_row_id", name="uq_sales_invoice_source_row"),
    )
    op.create_index(
        "ix_sales_invoices_company_issue_date",
        "sales_invoices",
        ["company_id", "issue_date"],
        unique=False,
    )
    op.create_index(
        "ix_sales_invoices_counterparty", "sales_invoices", ["counterparty_id"], unique=False
    )
    op.create_table(
        "journal_lines",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("source_row_id", sa.UUID(), nullable=False),
        sa.Column("debit_irr", sa.Numeric(precision=20, scale=0), nullable=False),
        sa.Column("credit_irr", sa.Numeric(precision=20, scale=0), nullable=False),
        sa.Column("counterparty_id", sa.UUID(), nullable=True),
        sa.Column("invoice_ref", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "NOT (debit_irr > 0 AND credit_irr > 0)", name="ck_journal_line_one_side"
        ),
        sa.CheckConstraint("credit_irr >= 0", name="ck_journal_line_credit_nonnegative"),
        sa.CheckConstraint("debit_irr >= 0", name="ck_journal_line_debit_nonnegative"),
        sa.ForeignKeyConstraint(
            ["account_id", "company_id"],
            ["accounts.id", "accounts.company_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["counterparty_id", "company_id"],
            ["counterparties.id", "counterparties.company_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entry_id", "company_id"],
            ["journal_entries.id", "journal_entries.company_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id", "company_id"],
            ["source_rows.id", "source_rows.company_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_row_id", name="uq_journal_line_source_row"),
    )
    op.create_index("ix_journal_lines_account", "journal_lines", ["account_id"], unique=False)
    op.create_index(
        "ix_journal_lines_company_entry", "journal_lines", ["company_id", "entry_id"], unique=False
    )
    for table in CANONICAL_TABLES:
        enable_rls(table)
    op.execute("ALTER TABLE public.account_classifications ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE public.account_classifications FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY account_classifications_select ON public.account_classifications "
        "FOR SELECT USING (private.has_company_role(company_id, "
        "ARRAY['OWNER','FINANCE_MANAGER','ADVISOR','VIEWER']))"
    )
    op.execute(
        "CREATE POLICY account_classifications_insert ON public.account_classifications "
        "FOR INSERT WITH CHECK (confirmed_by = private.current_user_id() AND "
        "private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']))"
    )
    op.execute("GRANT SELECT, INSERT ON public.account_classifications TO didban_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_journal_lines_company_entry", table_name="journal_lines")
    op.drop_index("ix_journal_lines_account", table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_index("ix_sales_invoices_counterparty", table_name="sales_invoices")
    op.drop_index("ix_sales_invoices_company_issue_date", table_name="sales_invoices")
    op.drop_table("sales_invoices")
    op.drop_index("ix_journal_entries_source_row", table_name="journal_entries")
    op.drop_index("ix_journal_entries_company_date", table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index("ix_bank_transactions_company_date", table_name="bank_transactions")
    op.drop_index("ix_bank_transactions_bank_account", table_name="bank_transactions")
    op.drop_table("bank_transactions")
    op.drop_index("ix_bank_accounts_company_label", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_constraint("uq_data_source_company", "data_sources", type_="unique")
    op.drop_index("ix_account_classifications_confirmed_by", table_name="account_classifications")
    op.drop_index(
        "ix_account_classifications_company_account", table_name="account_classifications"
    )
    op.drop_table("account_classifications")
    op.drop_index("ix_counterparties_company_national_id", table_name="counterparties")
    op.drop_table("counterparties")
    op.drop_index("ix_accounts_company_normalized_name", table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
