"""phase 3 secure import intake

Revision ID: 6702092c0984
Revises: 175d6e14d397
Create Date: 2026-09-12 19:27:53.817556
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

RLS_SQL = """
ALTER TABLE public.data_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY data_sources_select ON public.data_sources FOR SELECT
USING (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR','VIEWER']));
CREATE POLICY data_sources_insert ON public.data_sources FOR INSERT
WITH CHECK (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']));

ALTER TABLE public.source_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.source_files FORCE ROW LEVEL SECURITY;
CREATE POLICY source_files_select ON public.source_files FOR SELECT
USING (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR','VIEWER']));
CREATE POLICY source_files_insert ON public.source_files FOR INSERT
WITH CHECK (
  uploaded_by = private.current_user_id()
  AND private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR'])
);
CREATE POLICY source_files_update ON public.source_files FOR UPDATE
USING (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']))
WITH CHECK (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']));

ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_batches FORCE ROW LEVEL SECURITY;
CREATE POLICY import_batches_select ON public.import_batches FOR SELECT
USING (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR','VIEWER']));
CREATE POLICY import_batches_insert ON public.import_batches FOR INSERT
WITH CHECK (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']));
CREATE POLICY import_batches_update ON public.import_batches FOR UPDATE
USING (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']))
WITH CHECK (private.has_company_role(company_id, ARRAY['OWNER','FINANCE_MANAGER','ADVISOR']));

GRANT SELECT, INSERT, UPDATE ON public.data_sources TO didban_app;
GRANT SELECT, INSERT, UPDATE ON public.source_files TO didban_app;
GRANT SELECT, INSERT, UPDATE ON public.import_batches TO didban_app;
"""

revision: str = "6702092c0984"
down_revision: str | None = "175d6e14d397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def execute_sql_script(script: str) -> None:
    for statement in script.split(";"):
        if statement.strip():
            op.execute(statement)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("ACCOUNTING", "BANK", "SALES", name="source_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_sources_company_kind", "data_sources", ["company_id", "kind"], unique=False
    )
    op.create_index("ix_data_sources_created_by", "data_sources", ["created_by"], unique=False)
    op.create_table(
        "source_files",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("extension", sa.String(length=12), nullable=False),
        sa.Column(
            "scan_status",
            sa.Enum(
                "PENDING", "CLEAN", "INFECTED", "FAILED", name="file_scan_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("scan_result", sa.String(length=255), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("duplicate_of_id", sa.UUID(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["source_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(
        "ix_source_files_company_created",
        "source_files",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_source_files_company_sha256", "source_files", ["company_id", "sha256"], unique=False
    )
    op.create_index(
        "ix_source_files_duplicate_of_id", "source_files", ["duplicate_of_id"], unique=False
    )
    op.create_index("ix_source_files_uploaded_by", "source_files", ["uploaded_by"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "INSPECTING",
                "AWAITING_MAPPING",
                "VALIDATING",
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "COMPLETED_LIMITED",
                "FAILED",
                "CANCELLED",
                name="import_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("coverage_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("progress >= 0 AND progress <= 100", name="ck_import_progress_range"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["source_files.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["data_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "idempotency_key", name="uq_import_company_idempotency"),
        sa.UniqueConstraint("file_id", name="uq_import_batches_file"),
    )
    op.create_index(
        "ix_import_batches_company_created",
        "import_batches",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_import_batches_company_status", "import_batches", ["company_id", "status"], unique=False
    )
    op.create_index("ix_import_batches_source_id", "import_batches", ["source_id"], unique=False)
    # ### end Alembic commands ###
    execute_sql_script(RLS_SQL)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_import_batches_source_id", table_name="import_batches")
    op.drop_index("ix_import_batches_company_status", table_name="import_batches")
    op.drop_index("ix_import_batches_company_created", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_source_files_uploaded_by", table_name="source_files")
    op.drop_index("ix_source_files_duplicate_of_id", table_name="source_files")
    op.drop_index("ix_source_files_company_sha256", table_name="source_files")
    op.drop_index("ix_source_files_company_created", table_name="source_files")
    op.drop_table("source_files")
    op.drop_index("ix_data_sources_created_by", table_name="data_sources")
    op.drop_index("ix_data_sources_company_kind", table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
